"use client"

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import Header from "@/components/header";
import { useState } from "react";
import useProductStore from "@/store/product/productStore";
import { ProductType } from "@/types/product.types";

const inter = Inter({ subsets: ["latin"] });

// export  const metadata: Metadata = {
//   title: "Alif shop",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { products } = useProductStore();
  const [filteredProducts, setFilteredProducts] = useState<ProductType[]>([]);

  const searchProducts = (query: string) => {
    const filteredProducts = products.filter((product) => {
      const searchInTitle = product.title
        .toLowerCase()
        .includes(query.toLowerCase());
      const searchInDescription = product.description
        .toLowerCase()
        .includes(query.toLowerCase());
      return searchInTitle || searchInDescription;
    });

    setFilteredProducts(filteredProducts);
  };

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header onSearch={searchProducts} />
        <main className="mt-28">{children}</main>
        <Footer />
      </body>
    </html>
  );
}

